name: docker-pipeline-vignesh
on: push
jobs:
 docker-job:
   runs-on: ubuntu-latest
   steps:
     - name: print-22itl08
       run: echo "Hello World - 22ITL08"

     - name: checkout
       uses: actions/checkout@v4

     - name: Docker Build
       run: docker build -t rakesh759/ml-model-22itl08 .

     - name: Docker Images
       run: docker images
       with:
         username: ${{ vars.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
